### ISSUE TITLE
Параметр ПодключитьБазуКхранилищу в функции СоздатьХранилищеКонфигурации, ошибка именования.

### ISSUE THREAD

**Issue by yehorh** [khorevaa/v8storage#17]
https://github.com/khorevaa/v8storage/blob/6402ce304d091f1558a4d2ff4fedeab36be17e26/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8.os#L332

`ПодключитьБазуКхранилищу` по смыслу должно подключать, а не отменять подключение к новому хранилищу.

**Comment by khorevaa** [comment]
Да бага

**Comment by GenVP** [comment]
Исправлено в 0.9.1
