### ISSUE TITLE
Не обрабатывается КаталогВыгрузкиРезультат в СписокОбъектовКонфигурации.ПолучитьПутьОбъектаИзФайлаВыгрузкиXML()

### ISSUE THREAD

**Issue by 1cgh** [khorevaa/v8storage#21]
Не обрабатывается КаталогВыгрузкиРезультат в СписокОбъектовКонфигурации.ПолучитьПутьОбъектаИзФайлаВыгрузкиXML() на разные слеши.

В полном имени файла выгрузки слеши приводятся к единому виду:
`ПолноеИмяФайлаВыгрузкиXML = СтрЗаменить(ПолноеИмяФайлаВыгрузкиXML, "\", "/");`
А в каталоге выгрузки - нет. Это может приводить к ошибке при получении имени объекта, если КаталогВыгрузкиРезультат содержит разные слеши. Не отработает
```
    // Удаляем каталог выгрузки из пути объекта.
    ИмяОбъекта = СтрЗаменить(ИмяОбъекта, КаталогВыгрузкиРезультат, "");
```

Необходимо добавить:
`    КаталогВыгрузкиРезультат = СтрЗаменить(КаталогВыгрузкиРезультат, "\", "/");`

**Comment by khorevaa** [comment]
Исправлено
