### ISSUE TITLE
Добавить возможность выгрузки комментариев хранилиша с //

### ISSUE THREAD

**Issue by abirambul** [khorevaa/v8storage#27]
С версии 8.3.17 добавлен новый параметр -IncludeCommentLinesWithDoubleSlash к /ConfigurationRepositoryReport ( https://its.1c.ru/db/v8317doc#bookmark:adm:TI000000807)

https://github.com/oscript-library/gitsync/issues/162

**Comment by khorevaa** [comment]
Выпущено в  версии 0.9.3
