### ISSUE TITLE
Не верно определяет комментарий к версии, если есть метка

### ISSUE THREAD

**Issue by Ndochp** [khorevaa/v8storage#29]
Не верно определяет комментарий к версии, если есть метка

Версия библиотеки 0.9.2
В архиве отчет по хранилищу, сформирован 1С:Предприятие 8.3 (8.3.17.1386)

При указании метки в отчете появляются разделы "Метка:", "Комментарий метки:" которые не предусмотрены как колонки функцией "СформироватьТаблицуВерсий" в "ПарсерХранилища.os".

В результате в комментарий последовательно пишется сам комментарий, заголовки этих разделов, и в итоге остаётся или комментарий к метке или текст "Комментарий метки:" .

[ver.zip](https://github.com/khorevaa/v8storage/files/5659546/ver.zip)

Всплыло при работе гитсинка, к сожалению не настолько разобрался в OS, чтобы выделить проблему в чистом виде.

**Comment by Ndochp** [comment]
Вроде разобрался с тестами и даже починил, постараюсь завтра собрать PR.

**Comment by khorevaa** [comment]
0.9.4
